export const Images = {
  logo: require('./images/LogoBG.png'),
  waves: require('./images/waves.png'),
  land1: require('./images/land1.png'),
  land2: require('./images/land2.png'),
  profileicon: require('./images/profileicon.png'),
  scanner: require('./images/scanner.png'),
  secure: require('./images/secure.png'),
  assets: require('./images/assets.png'),
  explore: require('./images/explore.png'),
  home: require('./images/home.png'),
  trade: require('./images/trade.png'),
  down:require('./images/down.png'),
  buy : require('./images/buy.png'),
  earn : require('./images/earn.png'),
  recieve : require('./images/recieve.png'),
  send : require('./images/send.png'),
  coinlogo : require('./images/coinlogo.png'),
  tradelogo : require('./images/trade.png'),
  pros: require('./images/pros.png'),
  cross:require('./images/cross.png'),
  projects: require('./images/Projectsmain.png'),
  projectlogo: require('./images/projectlogo.png'),
  list1: require('./images/list1.png'),
  list2: require('./images/list2.png'),
  list3: require('./images/list3.png'),
  list4: require('./images/list4.png'),
  list5: require('./images/list5.png'),
  list6: require('./images/list6.png'),
  backscreen: require('./images/backscreen.png'),
  comment: require('./images/comment.png'),
  iconcircle:require('./images/iconcircle.png'),
  prosimage: require('./images/prosimage.png'),
  crossoverlay: require('./images/closeoverlay.png'),
  primary: require('./images/primary.png'),
  primary1: require('./images/primary1.png'),
  primary2: require('./images/primary2.png'),
  social: require('./images/social.png'),
  nfts: require('./images/nfts.png'),
  trade1: require('./images/trade1.png'),
  trade2: require('./images/trade2.png'),
  earn1: require('./images/earn1.png'),
  earn2: require('./images/earn2.png'),
  bottomhead: require('./images/bottomhead.png'),
  up: require('./images/up.png'),
  checked: require('./images/checked.png'),
  back: require ('./images/back.png'),
  probadge: require('./images/probadge.png'),
  checked1: require('./images/checked1.png'),
  securityicon:require('./images/securityicon.png'),
identity:require('./images/identity.png'),
connections:require('./images/connections.png'),
referrals:require('./images/referrals.png'),
notifications:require('./images/notifications.png'),
contacts:require('./images/contacts.png'),
helpsupport:require('./images/helpsupport.png'),
forward:require('./images/forward.png'),
pro:require('./images/pro.png'),
secureicon:require('./images/secureicon.png'),
tick:require('./images/tick.png'),
downarrow:require('./images/downarrow.png'),
refresh:require('./images/refresh.png'),
whitecross:require('./images/whitecross.png'),
vaulticon:require('./images/vaulticon.png'),
solanalogo: require('./images/solanalogo.png'),
solanabg: require('./images/solanabg.png'),
backarrow: require('./images/backarrow.png'),
copy: require('./images/COPY.png')

}
